Feature/filters sor and ror
Marcus-Forte/pointcloud-tools pull request #6
Opened 2024-04-23 19:14 UTC by sedoski-duna

2024-04-24 22:44 UTC, Marcus-Forte commented
ficou show! no geral, talvez dê pra melhorar o uso de exceptions em vez de passar erro via arg

outra coisa, sobre a factory, talvez um pattern desse seja interessante:
![image](https://github.com/Marcus-Forte/pointcloud-tools/assets/18338626/7126444b-847f-4351-95e8-77e3974d5d43)


assim vc implementa apenas os m[etodos privadas/protected , e a classe base força a regra de chamar validate antes do apply.

2024-04-24 22:46 UTC, Marcus-Forte requested changes

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/include/filter_factory.h
> +  namespace filter_factory
pode deixar namespace `factory` apenas, já que o nome do método da factory sugere o objeto que é criado

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/include/filter.h
> +    virtual bool validateParameters(std::vector<float> parameters, std::string &errorMessage) = 0;
melhor fazer um `const std::vector<float>& parameters`, pra evitar copy. A error message pode ser `std::string` mesmo caso usemos algum move internamente

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/include/filter.h
> +    virtual bool validateParameters(std::vector<float> parameters, std::string &errorMessage) = 0;
esse comment aplica pras classes filhas tbm

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/include/filter.h
> +class Filter
pode renomear pra `IFilter` (o nome do arquivo tbm) pra deixar claro que eh uma interface

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/include/filter.h
> +    virtual pcl::PointCloud<PointT>::Ptr applyFilter(std::vector<float>& parameters, pcl::PointCloud<PointT>::Ptr input, std::string& errorMessage) = 0;
achei um pouco confuso a errorMessage ser passada via arg. não seria melhor fazer `throw std::runtime_error` internamente?

idealmente fariamos nossas próprias exceptions mas uma runtime_error tá ok

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/src/filter.cpp
> +        std::cerr << "Exception: " << ex.what() << std::endl;
seguindo a ideia do comment sobre errorMessage, aqui seria poderiamos fazer outro `throw` mais informativo, em vez de popular o errorMessage

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/src/filter_factory.cpp
> +        break;
pode tirar o break já que tem return logo acima

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/src/filter_factory.cpp
> +        return nullptr;
eh melhor jogar uma exception aqui talvez?

2024-04-24 22:46 UTC, Marcus-Forte commented on grpc/src/filter_services.cpp
> +void log(std::string message)
show

2024-04-29 16:56 UTC, sedoski-duna commented on grpc/src/filter_factory.cpp
> +        return nullptr;
Done

2024-04-29 17:01 UTC, sedoski-duna commented on grpc/src/filter.cpp
> +        std::cerr << "Exception: " << ex.what() << std::endl;
Feito

2024-04-29 17:02 UTC, sedoski-duna commented on grpc/include/filter.h
> +    virtual pcl::PointCloud<PointT>::Ptr applyFilter(std::vector<float>& parameters, pcl::PointCloud<PointT>::Ptr input, std::string& errorMessage) = 0;
Criei algumas custom exceptions para alinhar com os possiveis codigos de erro retornados na grpc call

2024-04-29 17:02 UTC, sedoski-duna commented on grpc/include/filter.h
> +class Filter
Feito

2024-04-29 17:03 UTC, sedoski-duna commented on grpc/include/filter.h
> +    virtual bool validateParameters(std::vector<float> parameters, std::string &errorMessage) = 0;
Feito

2024-04-29 17:03 UTC, sedoski-duna commented on grpc/include/filter_factory.h
> +  namespace filter_factory
ok

2024-04-30 17:14 UTC, merged